### ISSUE TITLE
Concept about the name of network

### ISSUE THREAD

**Issue by sh0416** [muhanzhang/DGCNN#4]
I just wondering why the name contains deep.
This network cannot deep.. which part can be deep? you mean the last part?
We cannot add graph convolutional layer in the first part of network. Right?

**Comment by muhanzhang** [comment]
No, by deep I mean the number of graph convolution layers can be (and should be) big. One reason is that the graph convolution results from different depth are concatenated so making it deep won't lose shallow information. The other reason is that the final graph convolution layer output is used to sort vertices. To make the order have as few ties as possible, we should make the graph convolution layers deep enough since graph convolution acts like continuous Weisfeiler-Lehman algorithm.

**Comment by sh0416** [comment]
Thanks for your valuable advice :)
