### ISSUE TITLE
How do you sort matrix rows?

### ISSUE THREAD

**Issue by JanoschMenke** [muhanzhang/DGCNN#9]
Hi I was wondering how exactly the rows are sorted during the pooling. If my output matrix Z from the last graph convolution is of size (n x f). Where f is the number of feature channels. How do I sort the rows? Or more in detail which channels do I use for sorting the vertexs?

**Comment by muhanzhang** [comment]
Hi, ideally we first sort rows according to the f-th channel, and then break (if any) ties by sorting by the (f-1)-th channel, and so on. In the implementation, we only sort according to the f-th channel and then stop, for efficiency concerns.

**Comment by JanoschMenke** [comment]
Just to be sure the f-th channel is the "last" channel. Is that choice not a little abitrary. I understand why it makes sense to use the last convolutions output to sort but why the last channel?

**Comment by muhanzhang** [comment]
Good question. It is because using the last convolution results to sort still need to sort dimension-wise. It is arbitrary to define your sorting order within the last convolution's channels. To make this easier, I only use 1 channel in the last convolution. Even you have multiple channels in the last convolution, I still recommend sorting from the last channel to previous channels, as it corresponds to an inverse lexicographical order.

**Comment by JanoschMenke** [comment]
Ah okay, thats what I thought but I was not sure. Many thanks for the quick answer.
